name: app_expenses
description: "Flutter expense control app with voice commands"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  intl: ^0.19.0
  fl_chart: ^0.66.2
  sqflite: ^2.3.0
  path: ^1.8.3
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.2
  sqflite_common_ffi: ^2.3.0+4

flutter:
  uses-material-design: true